---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code    
        uses: actions/checkout@v2.3.4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20 
      - run: yarn install   #Installing dependencies
      - run: yarn lint 
        env:
         ESLINT_USE_FLAT_CONFIG: false  #exit code 2: 2: Linting was unsuccessful due to a configuration problem or an internal error.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
           context: .
           push: true
           tags: bertolddewaele/webapp:latest



